/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { AnkrEth, AnkrEthInterface } from "../AnkrEth";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "bondsToShares",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sharesToBonds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AnkrEth__factory {
  static readonly abi = _abi;
  static createInterface(): AnkrEthInterface {
    return new utils.Interface(_abi) as AnkrEthInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AnkrEth {
    return new Contract(address, _abi, signerOrProvider) as AnkrEth;
  }
}
