/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICvxLockerV2, ICvxLockerV2Interface } from "../ICvxLockerV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_spendRatio",
        type: "uint256",
      },
    ],
    name: "lock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICvxLockerV2__factory {
  static readonly abi = _abi;
  static createInterface(): ICvxLockerV2Interface {
    return new utils.Interface(_abi) as ICvxLockerV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICvxLockerV2 {
    return new Contract(address, _abi, signerOrProvider) as ICvxLockerV2;
  }
}
