/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFrxETHMinter, IFrxETHMinterInterface } from "../IFrxETHMinter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "submitAndDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IFrxETHMinter__factory {
  static readonly abi = _abi;
  static createInterface(): IFrxETHMinterInterface {
    return new utils.Interface(_abi) as IFrxETHMinterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFrxETHMinter {
    return new Contract(address, _abi, signerOrProvider) as IFrxETHMinter;
  }
}
