/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IStEthEthPool, IStEthEthPoolInterface } from "../IStEthEthPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "int128",
        name: "i",
        type: "int128",
      },
      {
        internalType: "int128",
        name: "j",
        type: "int128",
      },
      {
        internalType: "uint256",
        name: "dx",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "min_dy",
        type: "uint256",
      },
    ],
    name: "exchange",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IStEthEthPool__factory {
  static readonly abi = _abi;
  static createInterface(): IStEthEthPoolInterface {
    return new utils.Interface(_abi) as IStEthEthPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStEthEthPool {
    return new Contract(address, _abi, signerOrProvider) as IStEthEthPool;
  }
}
