/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  RocketDAOProtocolSettingsDepositInterface,
  RocketDAOProtocolSettingsDepositInterfaceInterface,
} from "../RocketDAOProtocolSettingsDepositInterface";

const _abi = [
  {
    inputs: [],
    name: "getAssignDepositsEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDepositEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDepositFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaximumDepositAssignments",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMaximumDepositPoolSize",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMinimumDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class RocketDAOProtocolSettingsDepositInterface__factory {
  static readonly abi = _abi;
  static createInterface(): RocketDAOProtocolSettingsDepositInterfaceInterface {
    return new utils.Interface(
      _abi
    ) as RocketDAOProtocolSettingsDepositInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RocketDAOProtocolSettingsDepositInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RocketDAOProtocolSettingsDepositInterface;
  }
}
