/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AfEthInterface extends utils.Interface {
  functions: {
    "CRV_ETH_CRV_POOL_ADDRESS()": FunctionFragment;
    "CVXCRV_CRV_CRV_POOL_ADDRESS()": FunctionFragment;
    "CVXFXS_FXS_CRV_POOL_ADDRESS()": FunctionFragment;
    "FXS_ETH_CRV_POOL_ADDRESS()": FunctionFragment;
    "addAfEthCrvLiquidity(address,uint256,uint256)": FunctionFragment;
    "claimRewards()": FunctionFragment;
    "getAsymmetryRatio()": FunctionFragment;
    "getCrvPriceData()": FunctionFragment;
    "getCvxPriceData()": FunctionFragment;
    "lockCvx(uint256)": FunctionFragment;
    "maxSlippage()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "positions(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "swapExactInputSingleHop(address,address,uint24,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawCRVPool(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CRV_ETH_CRV_POOL_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CVXCRV_CRV_CRV_POOL_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CVXFXS_FXS_CRV_POOL_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FXS_ETH_CRV_POOL_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAfEthCrvLiquidity",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAsymmetryRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCrvPriceData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCvxPriceData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockCvx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSlippage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "positions", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactInputSingleHop",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCRVPool",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CRV_ETH_CRV_POOL_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CVXCRV_CRV_CRV_POOL_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CVXFXS_FXS_CRV_POOL_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FXS_ETH_CRV_POOL_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAfEthCrvLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAsymmetryRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCrvPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCvxPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockCvx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxSlippage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactInputSingleHop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCRVPool",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface AfEth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AfEthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CRV_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    CVXCRV_CRV_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    CVXFXS_FXS_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    FXS_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    addAfEthCrvLiquidity(
      _pool: string,
      _ethAmount: BigNumberish,
      _afEthAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAsymmetryRatio(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { ratio: BigNumber }>;

    getCrvPriceData(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCvxPriceData(overrides?: CallOverrides): Promise<[BigNumber]>;

    lockCvx(
      _amountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxSlippage(overrides?: CallOverrides): Promise<[BigNumber]>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        positionID: BigNumber;
        curveBalances: BigNumber;
        convexBalances: BigNumber;
        cvxNFTID: BigNumber;
        bundleNFTID: BigNumber;
        afETH: BigNumber;
        createdAt: BigNumber;
      }
    >;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    swapExactInputSingleHop(
      tokenIn: string,
      tokenOut: string,
      poolFee: BigNumberish,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawCRVPool(
      _pool: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CRV_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

  CVXCRV_CRV_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

  CVXFXS_FXS_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

  FXS_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

  addAfEthCrvLiquidity(
    _pool: string,
    _ethAmount: BigNumberish,
    _afEthAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimRewards(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAsymmetryRatio(overrides?: CallOverrides): Promise<BigNumber>;

  getCrvPriceData(overrides?: CallOverrides): Promise<BigNumber>;

  getCvxPriceData(overrides?: CallOverrides): Promise<BigNumber>;

  lockCvx(
    _amountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxSlippage(overrides?: CallOverrides): Promise<BigNumber>;

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  positions(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      positionID: BigNumber;
      curveBalances: BigNumber;
      convexBalances: BigNumber;
      cvxNFTID: BigNumber;
      bundleNFTID: BigNumber;
      afETH: BigNumber;
      createdAt: BigNumber;
    }
  >;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  swapExactInputSingleHop(
    tokenIn: string,
    tokenOut: string,
    poolFee: BigNumberish,
    amountIn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawCRVPool(
    _pool: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CRV_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

    CVXCRV_CRV_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

    CVXFXS_FXS_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

    FXS_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<string>;

    addAfEthCrvLiquidity(
      _pool: string,
      _ethAmount: BigNumberish,
      _afEthAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimRewards(overrides?: CallOverrides): Promise<void>;

    getAsymmetryRatio(overrides?: CallOverrides): Promise<BigNumber>;

    getCrvPriceData(overrides?: CallOverrides): Promise<BigNumber>;

    getCvxPriceData(overrides?: CallOverrides): Promise<BigNumber>;

    lockCvx(
      _amountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxSlippage(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        positionID: BigNumber;
        curveBalances: BigNumber;
        convexBalances: BigNumber;
        cvxNFTID: BigNumber;
        bundleNFTID: BigNumber;
        afETH: BigNumber;
        createdAt: BigNumber;
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    swapExactInputSingleHop(
      tokenIn: string,
      tokenOut: string,
      poolFee: BigNumberish,
      amountIn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawCRVPool(
      _pool: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    CRV_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    CVXCRV_CRV_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    CVXFXS_FXS_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    FXS_ETH_CRV_POOL_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    addAfEthCrvLiquidity(
      _pool: string,
      _ethAmount: BigNumberish,
      _afEthAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAsymmetryRatio(overrides?: CallOverrides): Promise<BigNumber>;

    getCrvPriceData(overrides?: CallOverrides): Promise<BigNumber>;

    getCvxPriceData(overrides?: CallOverrides): Promise<BigNumber>;

    lockCvx(
      _amountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxSlippage(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    positions(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactInputSingleHop(
      tokenIn: string,
      tokenOut: string,
      poolFee: BigNumberish,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawCRVPool(
      _pool: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CRV_ETH_CRV_POOL_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CVXCRV_CRV_CRV_POOL_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CVXFXS_FXS_CRV_POOL_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    FXS_ETH_CRV_POOL_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAfEthCrvLiquidity(
      _pool: string,
      _ethAmount: BigNumberish,
      _afEthAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimRewards(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAsymmetryRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCrvPriceData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCvxPriceData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockCvx(
      _amountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxSlippage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    positions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapExactInputSingleHop(
      tokenIn: string,
      tokenOut: string,
      poolFee: BigNumberish,
      amountIn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawCRVPool(
      _pool: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
