/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AnkrEthInterface extends utils.Interface {
  functions: {
    "bondsToShares(uint256)": FunctionFragment;
    "sharesToBonds(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bondsToShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesToBonds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bondsToShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesToBonds",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AnkrEth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AnkrEthInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bondsToShares(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    sharesToBonds(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  bondsToShares(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  sharesToBonds(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    bondsToShares(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sharesToBonds(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    bondsToShares(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sharesToBonds(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bondsToShares(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sharesToBonds(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
