/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IClaimZapInterface extends utils.Interface {
  functions: {
    "claimRewards(address[],address[],address[],address[],uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "claimRewards",
    values: [
      string[],
      string[],
      string[],
      string[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IClaimZap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IClaimZapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claimRewards(
      rewardContracts: string[],
      extraRewardContracts: string[],
      tokenRewardContracts: string[],
      tokenRewardTokens: string[],
      depositCrvMaxAmount: BigNumberish,
      minAmountOut: BigNumberish,
      depositCvxMaxAmount: BigNumberish,
      spendCvxAmount: BigNumberish,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  claimRewards(
    rewardContracts: string[],
    extraRewardContracts: string[],
    tokenRewardContracts: string[],
    tokenRewardTokens: string[],
    depositCrvMaxAmount: BigNumberish,
    minAmountOut: BigNumberish,
    depositCvxMaxAmount: BigNumberish,
    spendCvxAmount: BigNumberish,
    options: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    claimRewards(
      rewardContracts: string[],
      extraRewardContracts: string[],
      tokenRewardContracts: string[],
      tokenRewardTokens: string[],
      depositCrvMaxAmount: BigNumberish,
      minAmountOut: BigNumberish,
      depositCvxMaxAmount: BigNumberish,
      spendCvxAmount: BigNumberish,
      options: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    claimRewards(
      rewardContracts: string[],
      extraRewardContracts: string[],
      tokenRewardContracts: string[],
      tokenRewardTokens: string[],
      depositCrvMaxAmount: BigNumberish,
      minAmountOut: BigNumberish,
      depositCvxMaxAmount: BigNumberish,
      spendCvxAmount: BigNumberish,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claimRewards(
      rewardContracts: string[],
      extraRewardContracts: string[],
      tokenRewardContracts: string[],
      tokenRewardTokens: string[],
      depositCrvMaxAmount: BigNumberish,
      minAmountOut: BigNumberish,
      depositCvxMaxAmount: BigNumberish,
      spendCvxAmount: BigNumberish,
      options: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
