/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RocketDAOProtocolSettingsDepositInterfaceInterface
  extends utils.Interface {
  functions: {
    "getAssignDepositsEnabled()": FunctionFragment;
    "getDepositEnabled()": FunctionFragment;
    "getDepositFee()": FunctionFragment;
    "getMaximumDepositAssignments()": FunctionFragment;
    "getMaximumDepositPoolSize()": FunctionFragment;
    "getMinimumDeposit()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAssignDepositsEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumDepositAssignments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumDepositPoolSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumDeposit",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssignDepositsEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumDepositAssignments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumDepositPoolSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumDeposit",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RocketDAOProtocolSettingsDepositInterface
  extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RocketDAOProtocolSettingsDepositInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAssignDepositsEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    getDepositEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    getDepositFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaximumDepositAssignments(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaximumDepositPoolSize(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMinimumDeposit(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getAssignDepositsEnabled(overrides?: CallOverrides): Promise<boolean>;

  getDepositEnabled(overrides?: CallOverrides): Promise<boolean>;

  getDepositFee(overrides?: CallOverrides): Promise<BigNumber>;

  getMaximumDepositAssignments(overrides?: CallOverrides): Promise<BigNumber>;

  getMaximumDepositPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

  getMinimumDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getAssignDepositsEnabled(overrides?: CallOverrides): Promise<boolean>;

    getDepositEnabled(overrides?: CallOverrides): Promise<boolean>;

    getDepositFee(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumDepositAssignments(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumDepositPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumDeposit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getAssignDepositsEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositFee(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumDepositAssignments(overrides?: CallOverrides): Promise<BigNumber>;

    getMaximumDepositPoolSize(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumDeposit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssignDepositsEnabled(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaximumDepositAssignments(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaximumDepositPoolSize(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinimumDeposit(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
