/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RocketStorageInterfaceInterface extends utils.Interface {
  functions: {
    "addUint(bytes32,uint256)": FunctionFragment;
    "confirmGuardian()": FunctionFragment;
    "confirmWithdrawalAddress(address)": FunctionFragment;
    "deleteAddress(bytes32)": FunctionFragment;
    "deleteBool(bytes32)": FunctionFragment;
    "deleteBytes(bytes32)": FunctionFragment;
    "deleteBytes32(bytes32)": FunctionFragment;
    "deleteInt(bytes32)": FunctionFragment;
    "deleteString(bytes32)": FunctionFragment;
    "deleteUint(bytes32)": FunctionFragment;
    "getAddress(bytes32)": FunctionFragment;
    "getBool(bytes32)": FunctionFragment;
    "getBytes(bytes32)": FunctionFragment;
    "getBytes32(bytes32)": FunctionFragment;
    "getDeployedStatus()": FunctionFragment;
    "getGuardian()": FunctionFragment;
    "getInt(bytes32)": FunctionFragment;
    "getNodePendingWithdrawalAddress(address)": FunctionFragment;
    "getNodeWithdrawalAddress(address)": FunctionFragment;
    "getString(bytes32)": FunctionFragment;
    "getUint(bytes32)": FunctionFragment;
    "setAddress(bytes32,address)": FunctionFragment;
    "setBool(bytes32,bool)": FunctionFragment;
    "setBytes(bytes32,bytes)": FunctionFragment;
    "setBytes32(bytes32,bytes32)": FunctionFragment;
    "setGuardian(address)": FunctionFragment;
    "setInt(bytes32,int256)": FunctionFragment;
    "setString(bytes32,string)": FunctionFragment;
    "setUint(bytes32,uint256)": FunctionFragment;
    "setWithdrawalAddress(address,address,bool)": FunctionFragment;
    "subUint(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmWithdrawalAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteInt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteUint",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBool", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getInt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getNodePendingWithdrawalAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeWithdrawalAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getUint", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "setGuardian", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setInt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalAddress",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "subUint",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodePendingWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setInt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subUint", data: BytesLike): Result;

  events: {};
}

export interface RocketStorageInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RocketStorageInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    confirmWithdrawalAddress(
      _nodeAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getDeployedStatus(overrides?: CallOverrides): Promise<[boolean]>;

    getGuardian(overrides?: CallOverrides): Promise<[string]>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    getNodePendingWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getNodeWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWithdrawalAddress(
      _nodeAddress: string,
      _newWithdrawalAddress: string,
      _confirm: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addUint(
    _key: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  confirmGuardian(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  confirmWithdrawalAddress(
    _nodeAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteAddress(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBool(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytes(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytes32(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteInt(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteString(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteUint(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getDeployedStatus(overrides?: CallOverrides): Promise<boolean>;

  getGuardian(overrides?: CallOverrides): Promise<string>;

  getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  getNodePendingWithdrawalAddress(
    _nodeAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getNodeWithdrawalAddress(
    _nodeAddress: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getString(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  setAddress(
    _key: BytesLike,
    _value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBool(
    _key: BytesLike,
    _value: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytes(
    _key: BytesLike,
    _value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytes32(
    _key: BytesLike,
    _value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGuardian(
    _newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInt(
    _key: BytesLike,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setString(
    _key: BytesLike,
    _value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUint(
    _key: BytesLike,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWithdrawalAddress(
    _nodeAddress: string,
    _newWithdrawalAddress: string,
    _confirm: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  subUint(
    _key: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmGuardian(overrides?: CallOverrides): Promise<void>;

    confirmWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteAddress(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBool(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBytes(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteInt(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteString(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteUint(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getDeployedStatus(overrides?: CallOverrides): Promise<boolean>;

    getGuardian(overrides?: CallOverrides): Promise<string>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getNodePendingWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getNodeWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setGuardian(_newAddress: string, overrides?: CallOverrides): Promise<void>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setWithdrawalAddress(
      _nodeAddress: string,
      _newWithdrawalAddress: string,
      _confirm: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    confirmWithdrawalAddress(
      _nodeAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getDeployedStatus(overrides?: CallOverrides): Promise<BigNumber>;

    getGuardian(overrides?: CallOverrides): Promise<BigNumber>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getNodePendingWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNodeWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWithdrawalAddress(
      _nodeAddress: string,
      _newWithdrawalAddress: string,
      _confirm: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    confirmWithdrawalAddress(
      _nodeAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAddress(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBool(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes32(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeployedStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGuardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInt(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodePendingWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNodeWithdrawalAddress(
      _nodeAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getString(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUint(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWithdrawalAddress(
      _nodeAddress: string,
      _newWithdrawalAddress: string,
      _confirm: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
